#!/bin/sh
# iptables
#

NAME=iptables
DESC="iptables initscript"
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    if [[ -f /etc/sysconfig/iptables-rules ]];
    then
        /usr/sbin/iptables-restore < /etc/sysconfig/iptables-rules
    else
        printf "%-50s" "No $NAME rules..."
    fi
;;
status)
        printf "%-50s" "Not supported"
;;
stop)
        printf "%-50s" "Flushing iptables rules"
    /usr/sbin/iptables -F
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
